# Generated by Django 5.0.4 on 2025-11-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_appointment_consultation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image"),
                    ("pdf", "PDF"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
