# Generated by Django 5.0.4 on 2025-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_chatmessage_attachment_chatmessage_attachment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
